description: A fun tutorial to light up your Flora NeoPixel with Arduino.
theme: minima

url: "https://lilaShiba.github.io"
baseurl: "sparkel"

markdown: kramdown
highlighter: rouge

social_links:
  github: "https://github.com/LilaShiba"
  twitter: "https://twitter.com/your-username"


# Custom CSS file link
assets:
  - "styles.css"
