title: 
description: A fun tutorial to light up your Flora NeoPixel with Arduino.
theme: minima

url: "https://lilaShiba.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

social_links:
  github: "https://github.com/LilaShiba"
  twitter: "https://twitter.com/your-username"

# header_pages:
#   - Home
#   - About
#   - Projects

# Custom CSS file link
# assets:
#   - "styles.css"
